"""add foreign key to onboarding

Revision ID: 3c6036948259
Revises: b9029cb240bb
Create Date: 2025-06-14 14:00:48.996337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c6036948259'
down_revision = 'b9029cb240bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('onboarding') as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_onboarding_employee_id',
            'employees',
            ['employee_id'],
            ['id']
        )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('onboarding') as batch_op:
        batch_op.drop_constraint('fk_onboarding_employee_id', type_='foreignkey')
        batch_op.drop_column('employee_id')
    # ### end Alembic commands ###